// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { GetScreenshotApiScreenshotsSessionIdFilenameGetData, GetScreenshotApiScreenshotsSessionIdFilenameGetErrors, GetScreenshotApiScreenshotsSessionIdFilenameGetResponses, GetScriptApiScriptsSessionIdTestPyGetData, GetScriptApiScriptsSessionIdTestPyGetErrors, GetScriptApiScriptsSessionIdTestPyGetResponses, GetSessionApiSessionsSessionIdGetData, GetSessionApiSessionsSessionIdGetErrors, GetSessionApiSessionsSessionIdGetResponses, GetStatsApiSessionsStatsGetData, GetStatsApiSessionsStatsGetResponses, GetWorkflowApiSessionsSessionIdWorkflowGetData, GetWorkflowApiSessionsSessionIdWorkflowGetErrors, GetWorkflowApiSessionsSessionIdWorkflowGetResponses, HealthApiHealthGetData, HealthApiHealthGetResponses, ManualCleanupApiSessionsCleanupPostData, ManualCleanupApiSessionsCleanupPostResponses, ProcessVideoApiSessionsSessionIdProcessPostData, ProcessVideoApiSessionsSessionIdProcessPostErrors, ProcessVideoApiSessionsSessionIdProcessPostResponses, RootGetData, RootGetResponses, StartAgentApiSessionsSessionIdStartPostData, StartAgentApiSessionsSessionIdStartPostErrors, StartAgentApiSessionsSessionIdStartPostResponses, UploadVideoApiVideosUploadPostData, UploadVideoApiVideosUploadPostErrors, UploadVideoApiVideosUploadPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Upload Video
 *
 * Upload a workflow video and create a session
 */
export const uploadVideoApiVideosUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadVideoApiVideosUploadPostData, ThrowOnError>) => {
    return (options.client ?? client).post<UploadVideoApiVideosUploadPostResponses, UploadVideoApiVideosUploadPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/videos/upload',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Get Session
 *
 * Get session information
 */
export const getSessionApiSessionsSessionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetSessionApiSessionsSessionIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSessionApiSessionsSessionIdGetResponses, GetSessionApiSessionsSessionIdGetErrors, ThrowOnError>({
        url: '/api/sessions/{session_id}',
        ...options
    });
};

/**
 * Get Workflow
 *
 * Get the processed workflow JSON for a session
 */
export const getWorkflowApiSessionsSessionIdWorkflowGet = <ThrowOnError extends boolean = false>(options: Options<GetWorkflowApiSessionsSessionIdWorkflowGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetWorkflowApiSessionsSessionIdWorkflowGetResponses, GetWorkflowApiSessionsSessionIdWorkflowGetErrors, ThrowOnError>({
        url: '/api/sessions/{session_id}/workflow',
        ...options
    });
};

/**
 * Process Video
 *
 * Process the uploaded video to extract workflow
 *
 * This runs in the background and updates status via WebSocket
 */
export const processVideoApiSessionsSessionIdProcessPost = <ThrowOnError extends boolean = false>(options: Options<ProcessVideoApiSessionsSessionIdProcessPostData, ThrowOnError>) => {
    return (options.client ?? client).post<ProcessVideoApiSessionsSessionIdProcessPostResponses, ProcessVideoApiSessionsSessionIdProcessPostErrors, ThrowOnError>({
        url: '/api/sessions/{session_id}/process',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Start Agent
 *
 * Start agent execution to generate test script
 */
export const startAgentApiSessionsSessionIdStartPost = <ThrowOnError extends boolean = false>(options: Options<StartAgentApiSessionsSessionIdStartPostData, ThrowOnError>) => {
    return (options.client ?? client).post<StartAgentApiSessionsSessionIdStartPostResponses, StartAgentApiSessionsSessionIdStartPostErrors, ThrowOnError>({
        url: '/api/sessions/{session_id}/start',
        ...options
    });
};

/**
 * Manual Cleanup
 *
 * Manually trigger session cleanup
 */
export const manualCleanupApiSessionsCleanupPost = <ThrowOnError extends boolean = false>(options?: Options<ManualCleanupApiSessionsCleanupPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<ManualCleanupApiSessionsCleanupPostResponses, unknown, ThrowOnError>({
        url: '/api/sessions/cleanup',
        ...options
    });
};

/**
 * Get Stats
 *
 * Get system statistics
 */
export const getStatsApiSessionsStatsGet = <ThrowOnError extends boolean = false>(options?: Options<GetStatsApiSessionsStatsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetStatsApiSessionsStatsGetResponses, unknown, ThrowOnError>({
        url: '/api/sessions/stats',
        ...options
    });
};

/**
 * Get Screenshot
 *
 * Serve screenshot files
 */
export const getScreenshotApiScreenshotsSessionIdFilenameGet = <ThrowOnError extends boolean = false>(options: Options<GetScreenshotApiScreenshotsSessionIdFilenameGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetScreenshotApiScreenshotsSessionIdFilenameGetResponses, GetScreenshotApiScreenshotsSessionIdFilenameGetErrors, ThrowOnError>({
        url: '/api/screenshots/{session_id}/{filename}',
        ...options
    });
};

/**
 * Get Script
 *
 * Serve generated test script
 */
export const getScriptApiScriptsSessionIdTestPyGet = <ThrowOnError extends boolean = false>(options: Options<GetScriptApiScriptsSessionIdTestPyGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetScriptApiScriptsSessionIdTestPyGetResponses, GetScriptApiScriptsSessionIdTestPyGetErrors, ThrowOnError>({
        url: '/api/scripts/{session_id}/test.py',
        ...options
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Health
 */
export const healthApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthApiHealthGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthApiHealthGetResponses, unknown, ThrowOnError>({
        url: '/api/health',
        ...options
    });
};
