// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { GetSessionApiSessionsSessionIdGetData, GetSessionApiSessionsSessionIdGetErrors, GetSessionApiSessionsSessionIdGetResponses, GetWorkflowApiSessionsSessionIdWorkflowGetData, GetWorkflowApiSessionsSessionIdWorkflowGetErrors, GetWorkflowApiSessionsSessionIdWorkflowGetResponses, HealthApiHealthGetData, HealthApiHealthGetResponses, ProcessVideoApiSessionsSessionIdProcessPostData, ProcessVideoApiSessionsSessionIdProcessPostErrors, ProcessVideoApiSessionsSessionIdProcessPostResponses, RootGetData, RootGetResponses, UploadVideoApiVideosUploadPostData, UploadVideoApiVideosUploadPostErrors, UploadVideoApiVideosUploadPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Upload Video
 *
 * Upload a workflow video and create a session
 */
export const uploadVideoApiVideosUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadVideoApiVideosUploadPostData, ThrowOnError>) => {
    return (options.client ?? client).post<UploadVideoApiVideosUploadPostResponses, UploadVideoApiVideosUploadPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/videos/upload',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Get Session
 *
 * Get session information
 */
export const getSessionApiSessionsSessionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetSessionApiSessionsSessionIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSessionApiSessionsSessionIdGetResponses, GetSessionApiSessionsSessionIdGetErrors, ThrowOnError>({
        url: '/api/sessions/{session_id}',
        ...options
    });
};

/**
 * Get Workflow
 *
 * Get the processed workflow JSON for a session
 */
export const getWorkflowApiSessionsSessionIdWorkflowGet = <ThrowOnError extends boolean = false>(options: Options<GetWorkflowApiSessionsSessionIdWorkflowGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetWorkflowApiSessionsSessionIdWorkflowGetResponses, GetWorkflowApiSessionsSessionIdWorkflowGetErrors, ThrowOnError>({
        url: '/api/sessions/{session_id}/workflow',
        ...options
    });
};

/**
 * Process Video
 *
 * Process the uploaded video to extract workflow
 *
 * This runs in the background and updates status via WebSocket
 */
export const processVideoApiSessionsSessionIdProcessPost = <ThrowOnError extends boolean = false>(options: Options<ProcessVideoApiSessionsSessionIdProcessPostData, ThrowOnError>) => {
    return (options.client ?? client).post<ProcessVideoApiSessionsSessionIdProcessPostResponses, ProcessVideoApiSessionsSessionIdProcessPostErrors, ThrowOnError>({
        url: '/api/sessions/{session_id}/process',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Health
 */
export const healthApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthApiHealthGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthApiHealthGetResponses, unknown, ThrowOnError>({
        url: '/api/health',
        ...options
    });
};
