// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_upload_video_api_videos_upload_post
 */
export type BodyUploadVideoApiVideosUploadPost = {
    /**
     * Video
     */
    video: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ProcessVideoRequest
 */
export type ProcessVideoRequest = {
    /**
     * Starting Url
     */
    starting_url: string;
    /**
     * Workflow Name
     */
    workflow_name?: string | null;
    /**
     * Workflow Description
     */
    workflow_description?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type UploadVideoApiVideosUploadPostData = {
    body: BodyUploadVideoApiVideosUploadPost;
    path?: never;
    query?: never;
    url: '/api/videos/upload';
};

export type UploadVideoApiVideosUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadVideoApiVideosUploadPostError = UploadVideoApiVideosUploadPostErrors[keyof UploadVideoApiVideosUploadPostErrors];

export type UploadVideoApiVideosUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSessionApiSessionsSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/sessions/{session_id}';
};

export type GetSessionApiSessionsSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSessionApiSessionsSessionIdGetError = GetSessionApiSessionsSessionIdGetErrors[keyof GetSessionApiSessionsSessionIdGetErrors];

export type GetSessionApiSessionsSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetWorkflowApiSessionsSessionIdWorkflowGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/sessions/{session_id}/workflow';
};

export type GetWorkflowApiSessionsSessionIdWorkflowGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowApiSessionsSessionIdWorkflowGetError = GetWorkflowApiSessionsSessionIdWorkflowGetErrors[keyof GetWorkflowApiSessionsSessionIdWorkflowGetErrors];

export type GetWorkflowApiSessionsSessionIdWorkflowGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProcessVideoApiSessionsSessionIdProcessPostData = {
    body: ProcessVideoRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/sessions/{session_id}/process';
};

export type ProcessVideoApiSessionsSessionIdProcessPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessVideoApiSessionsSessionIdProcessPostError = ProcessVideoApiSessionsSessionIdProcessPostErrors[keyof ProcessVideoApiSessionsSessionIdProcessPostErrors];

export type ProcessVideoApiSessionsSessionIdProcessPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
